'use client'

import { useEffect } from 'react'

/**
 * Service Worker Registration — registers custom-sw.js directly.
 * 
 * IMPORTANT: We register /custom-sw.js (our hand-written SW) instead of
 * /sw.js (generated by next-pwa/Workbox). The Workbox-generated SW was
 * conflicting with our navigation handler, causing offline cold-starts
 * to fail with ERR_FAILED because Workbox's own route handlers would
 * intercept navigations without a proper offline fallback.
 * 
 * After registration, we send a PRECACHE_URLS message to warm-up the
 * cache with critical pages while the user has an active session
 * (so the fetches include auth cookies and return real page HTML).
 */
export default function ServiceWorkerRegistration() {
  useEffect(() => {
    if ('serviceWorker' in navigator && (window.location.protocol === 'https:' || window.location.hostname === 'localhost')) {
      const registerSW = async () => {
        try {
          // Unregister any old Workbox-generated SW first
          const existingRegistrations = await navigator.serviceWorker.getRegistrations();
          for (const reg of existingRegistrations) {
            const swUrl = reg.active?.scriptURL || reg.installing?.scriptURL || reg.waiting?.scriptURL || '';
            if (swUrl.endsWith('/sw.js')) {
              console.log('[App] Unregistering old Workbox SW:', swUrl);
              await reg.unregister();
            }
          }

          // Register our custom SW
          const reg = await navigator.serviceWorker.register('/custom-sw.js', { scope: '/' });
          console.log('[App] Custom SW registered, scope:', reg.scope);

          // Force the new SW to activate immediately if waiting
          if (reg.waiting) {
            reg.waiting.postMessage('skipWaiting');
          }
          reg.addEventListener('updatefound', () => {
            const newWorker = reg.installing;
            if (newWorker) {
              newWorker.addEventListener('statechange', () => {
                if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                  newWorker.postMessage('skipWaiting');
                }
              });
            }
          });

          // Warm-up cache: pre-cache critical pages with auth cookies
          // Wait a moment for the SW to fully activate
          setTimeout(() => {
            warmUpCache();
          }, 3000);

          // Check for SW updates every 30 minutes
          setInterval(() => {
            reg.update();
          }, 30 * 60 * 1000);

        } catch (err) {
          console.error('[App] SW registration failed:', err);
        }
      };

      if (document.readyState === 'complete') {
        registerSW();
      } else {
        window.addEventListener('load', registerSW);
        return () => window.removeEventListener('load', registerSW);
      }
    }
  }, []);

  return null;
}

/**
 * Warm-up cache: sends a message to the active SW to pre-cache
 * critical pages. This runs AFTER mount, so the user is logged in
 * and fetch requests include session cookies, ensuring the cached
 * pages are the actual dashboard HTML (not login redirects).
 */
function warmUpCache() {
  if (!navigator.serviceWorker.controller) return;

  // Determine which role-specific pages to cache based on current URL
  const isOperator = window.location.pathname.includes('/operador');
  const isSubcon = window.location.pathname.includes('/subcontratista');

  const criticalPages = [
    '/admin',
    '/admin/',
    '/admin/login',
    '/admin/cotizaciones',
    '/admin/cotizaciones/',
    '/admin/inventario',
  ];

  if (isOperator) {
    criticalPages.push(
      '/admin/operador',
      '/admin/operador/',
      '/admin/operador/nuevo',
    );
  } else if (isSubcon) {
    criticalPages.push(
      '/admin/subcontratista',
    );
  } else {
    // Admin
    criticalPages.push(
      '/admin/proyectos',
      '/admin/recursos',
      '/admin/reportes',
    );
  }

  navigator.serviceWorker.controller.postMessage({
    type: 'PRECACHE_URLS',
    urls: criticalPages,
  });

  console.log('[App] Sent warm-up cache request for', criticalPages.length, 'pages');
}
